### ISSUE TITLE
wget not available (and not necessary?) on Mac

### ISSUE THREAD

**Issue by phkrief** [Agile-IoT/agile-stack#14]
Hi,
In README.md doc, it says:
Download the OS: wget https://files.resin.io/resinos/raspberrypi3/2.0.0-beta.1/resin-dev.zip

By default wget is not install on my Mac, so I was wondering if I could simply download the file using my web browser or does wget have a special role in this case ?
On the first case, we could maybe remove the wget from the instruction.
My 2 cents

Thanks

**Comment by craig-mulligan** [comment]
wget has no specific role, it just seemed like the easiest way to explain a download. Happy to accept PRs for browser instructions :)
