### ISSUE TITLE
ERROR: for agile-zb

### ISSUE THREAD

**Issue by phkrief** [Agile-IoT/agile-stack#15]
At the end of the deployment process (bash push.sh), I got the following error:
```
ERROR: for agile-zb  Cannot start service agile-zb: error gathering device information while adding custom device "dev/ttyUSB0": lstat dev/ttyUSB0: no such file or directory
ERROR: Encountered errors while bringing up the project.
```
@cskiraly told me it was not an issue on another context.
Can I assume it is not a context during this process as well?
In any cases, I wanted to keep track of that for other developers.

Thanks

**Comment by cskiraly** [comment]
The ZigBee protocol cannot start without the appropriate hardware. At the moment component initialization is not based on available hardware. We will have to handle this later on, so lets keep this open.

**Comment by cskiraly** [comment]
I have removed the ZB from the default deployment until we have the software for the new shield.
