### ISSUE TITLE
Device Discovery will not show it is turned ON on Device Manager

### ISSUE THREAD

**Issue by phkrief** [Agile-IoT/agile-stack#16]
I installed the latest containers and when I try to turn on in the settings the Device Discovery, a pop up will appear at the bottom on the browser saying it is turned ON bu the switch will stay OFF.
![image](https://cloud.githubusercontent.com/assets/6196602/23552405/fe49683c-001b-11e7-87e1-4a359f1a95f4.png)

It seems to be a regression because it worked with the workshop image.

Thanks

**Comment by craig-mulligan** [comment]
Hey @phkrief, It's because the UI is using the status from the API which currently has a bug when fetching discover status See here: https://github.com/Agile-IoT/agile-core/issues/39

**Comment by craig-mulligan** [comment]
This bug is tracked in the agile-core. Closing here.
