### ISSUE TITLE
docker-compose container naming

### ISSUE THREAD

**Issue by cskiraly** [Agile-IoT/agile-stack#18]
docker-compose automatically names containers based on the name of the containing folder. This, however, can change if we rename agile-stack (like we did), or if someone renames the folder of the git repo.
As a result, one would have two copies of containers trying to start .... leading to various issues.

@craig-mulligan @curcuz Do you know how to fix the prefix of generated container names in the compose file? I was browsing docs, but failed to find it.

**Comment by craig-mulligan** [comment]
@cskiraly it's called `container_name` https://docs.docker.com/compose/compose-file/#containername. I'll add it as an issue for the graz release
