### ISSUE TITLE
add agile-data service

### ISSUE THREAD

**Issue by craig-mulligan** [Agile-IoT/agile-stack#27]

**Comment by cskiraly** [comment]
Related branch in UI: https://github.com/Agile-IoT/agile-ui/tree/agile-data-ui

**Comment by cskiraly** [comment]
Stub is at https://github.com/Agile-IoT/agile-stack/tree/data-integration
@Exulansis @craig-mulligan, please develop this to a tested and mergeable state.

**Comment by cskiraly** [comment]
added in https://github.com/Agile-IoT/agile-stack/tree/data-integration
