### ISSUE TITLE
Publishing built containers

### ISSUE THREAD

**Issue by craig-mulligan** [Agile-IoT/agile-stack#3]
Once you have finished developing a new service it'd be nice if there was an easy way to push the built container to dockerhub.

Unfortunately, you can't just remotely login to the docker engine on the rpi host because it tries to write to `/var/lib/docker/config` but this is `read-only`. Possibly the best option is to do a remote `docker extract` then `docker load` into local machines daemon then push from there. 

Needs testing.

**Comment by craig-mulligan** [comment]
You can actually build arm images on your local machine. So no need to build it on the device.

**Comment by cskiraly** [comment]
There are two ways that work for me:
1, build on local machine in qemu ARM emulation. This is working for almost everything **except for java images**. You cab obviously push this with `docker push`.
2, build on the device, but managing the build process from your local machine. I.e., set up DOCKER_HOST to point to the manged device, then build using `docker build` or `docker-compose build` and finally `docker push`. This latter works fine over the DOCKER_HOST configured remote endpoint, and the managed device will nicely push the image to dockerhub.
