### ISSUE TITLE
waiting for Bluez to initialize

### ISSUE THREAD

**Issue by phkrief** [Agile-IoT/agile-stack#42]
Hi Folks,

I'm again stocked with this infinite message: 
     agile-ble                | waiting for Bluez to initialize

Am I supposed to run the command:
ssh root@resin.local -p22222 'mount -o remount,rw / && systemctl disable bluetooth && sed -i "s/i2c-dev/i2c-dev\n\/usr\/bin\/hciattach \/dev\/ttyAMA0 bcm43xx 921600 noflow -/" /usr/bin/resin-init-board && /sbin/reboot'

Each time I have to restart my RPi? I was not my understanding knowing the last instruction of this command reboots the RPi, so I assume that the RPi is correctly definitively configured after this instruction.

FYI, I could reach the last step and my SensorTag has been identified once. But when I had to restart my RPi, I failed to make it work.

So, could you tell me what are the instructions I should run if I want to restart by RPi once I when through the deployment (docker-compose up)?

Thanks

**Comment by cskiraly** [comment]
Hi @phkrief ,
The command makes permanent modifications, and it is meant to be run only once. 

Please debug using the following steps:
- start the Pi as it is now
- `ssh root@resin.local -p22222`
- verify that ssh went fine and you are logged on
- `hciconfig`
- you should see something like the following:
```
 hci0:	Type: Primary  Bus: UART
	BD Address: B8:27:EB:XX:XX:XX  ACL MTU: 1021:8  SCO MTU: 64:1
	UP RUNNING 
	RX bytes:1138 acl:0 sco:0 events:48 errors:0
	TX bytes:741 acl:0 sco:0 commands:52 errors:0
```
- If you see hci0, the problem is with container initialization. If you see another hciX, we could make the init more generic to pick up the first one. Anyway, you can currently set it in your `docker-compose.yml` to the correct one. If you don't see any hci interface check the following:
- that you actually have a Rasberry Pi 3 model B with embedded BLE :-)
- that `systemctl status bluetooth` shows disabled
- that `cat /usr/bin/resin-init-board` contains a line with `modprobe i2c-dev` and one with `/usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow -`
- that `dmesg` contains lines like these:
```
[   13.828333] Bluetooth: Core ver 2.21
[   13.832161] NET: Registered protocol family 31
[   13.836842] Bluetooth: HCI device and connection manager initialized
[   13.843428] Bluetooth: HCI socket layer initialized
[   13.848525] Bluetooth: L2CAP socket layer initialized
[   13.853788] Bluetooth: SCO socket layer initialized
[   13.891252] Bluetooth: HCI UART driver ver 2.3
[   13.896100] Bluetooth: HCI UART protocol H4 registered
[   13.901423] Bluetooth: HCI UART protocol Three-wire (H5) registered
[   13.910930] Bluetooth: HCI UART protocol BCM registered
[   13.936982] brcmfmac: power management disabled
```

**Comment by phkrief** [comment]
Thx a lot @cskiraly for taking time to answer.
I flashed again the SSD card and went through the full setup process again.
- So, Yes I do have and do use ;-) a RPi 3
- So, yes, If I open another window on
   ssh root@resin.local -p22222
  (Btw, this command is very slow to return the prompt, is it expected?)

and run 
   hciconfig
I get:

```
hci0:	Type: Primary  Bus: UART
	BD Address: B8:27:EB:20:A9:05  ACL MTU: 1021:8  SCO MTU: 64:1
	UP RUNNING 
	RX bytes:1378 acl:0 sco:0 events:76 errors:0
	TX bytes:1711 acl:0 sco:0 commands:76 errors:0
```
Is it expected ?
Now, if I can open a web browser on the page http://resin.local:8000/
I'm even able to fine the SensorTag in the list of devices:
```
agile-security           | GET /api/v1/entity/device/ble247189E85200 404 61.142 ms - 95
agile-ble                | 11:40:27.268 [pool-1-thread-1] DEBUG i.agile.protocol.ble.BLEProtocolImp - Checking for new devices
agile-ble                | 11:40:27.317 [Thread-1] INFO  i.agile.protocol.ble.BLEProtocolImp - Connected BLE device 24:71:89:E8:52:00
agile-devicefactory      | 11:40:27.320 [Thread-3] INFO  iot.agile.device.base.DeviceImp - Device connect ble247189E85200
agile-devicemanager      | 11:40:27.324 [Thread-8] INFO  i.a.devicemanager.DeviceManagerImp - Device connected
```
Unfortunatelly, after that, the AGILE web page says that there is a network issue.

Now, when I try to launch NodeRed, I get the error: 
```
Application 'ApplicationNodeRed' preloading failed: 
/packages/default/NodeRed/main.js
```
I double-checked the log generated by the command docker-compose up and it says:
```
agile-nodered            | 14 Dec 10:47:50 - [info] 
agile-nodered            | 
agile-nodered            | Welcome to Node-RED
agile-nodered            | ===================
agile-nodered            | 
agile-nodered            | 14 Dec 10:47:50 - [info] Node-RED version: v0.16.2
agile-nodered            | 14 Dec 10:47:50 - [info] Node.js  version: v7.8.0
agile-nodered            | 14 Dec 10:47:50 - [info] Linux 4.4.50 arm LE
agile-nodered            | 14 Dec 10:47:52 - [info] Loading palette nodes
agile-nodered            | 14 Dec 10:47:53 - [warn] Cannot find Pi RPi.GPIO python library
agile-nodered            | 14 Dec 10:47:56 - [info] Dashboard up and running
agile-nodered            | 14 Dec 10:47:59 - [info] Dashboard version 2.3.11 started at /api/ui
agile-nodered            | 14 Dec 10:48:00 - [warn] ------------------------------------------------------
agile-nodered            | 14 Dec 10:48:00 - [warn] [rpi-gpio] Warning : Cannot find Pi RPi.GPIO python library
agile-nodered            | 14 Dec 10:48:00 - [warn] ------------------------------------------------------
agile-nodered            | 14 Dec 10:48:00 - [info] User directory : /opt/secure-nodered/.nodered/
agile-nodered            | 14 Dec 10:48:00 - [info] Flows file     : /opt/secure-nodered/.nodered/flows_agile-nodered.json
agile-nodered            | 14 Dec 10:48:00 - [info] Creating new flow file
agile-nodered            | 14 Dec 10:48:00 - [info] Starting flows
agile-nodered            | 14 Dec 10:48:00 - [info] Started flows
```

Any explanation?

Thanks a lot

**Comment by cskiraly** [comment]
was a LAN configuration issue
