### ISSUE TITLE
git not installed on host

### ISSUE THREAD

**Issue by cskiraly** [Agile-IoT/agile-stack#8]
I was trying to use a docker-compose.yml which builds directly from git, but git seems not to be installed in the base image.

```
[...]
  agile-dbus:
    image: agileiot/agile-dbus-armv7l
    # build: apps/agile-dbus
    build: https://github.com/Agile-IoT/agile-dbus.git
[...]
```

```
bash-3.2$ AGILE_MODE=remote ./agile compose build
Building agile-dbus
ERROR: Error trying to use git: exec: "git": executable file not found in $PATH ()
```

I'm not sure will actually use this feature, but I think it would be nice to support in resinOS.
@curcuz , @craig-mulligan, if I'm not missing something, can you propagate this upstream?

**Comment by craig-mulligan** [comment]
@cskiraly, all our images with `buildpack-deps` will have git.(https://docs.resin.io/runtime/resin-base-images/) So probably best to just swap out the `alpine` image of agile-dbus for `debian` or install it ourselves.

**Comment by cskiraly** [comment]
@craig-mulligan, sorry, I was writing base image but I was thinking of the resinOS host file system. I was referring to git use as documented in https://docs.docker.com/compose/compose-file/#/build :  "Either a path to a directory containing a Dockerfile, or a url to a git repository."

I think you would need git to be installed on the host to make this docker-compose feature work.

**Comment by craig-mulligan** [comment]
Ah I see what you mean. Hmm interesting I guess for a resinOS dev image it'd make sense to have git available for that feature. You can just clone the repo locally in `/apps`, does that work in the meantime or is it blocking?

**Comment by cskiraly** [comment]
local path works fine. Having the possibility to have http links would be still nice (both for us and for resinOS in general), but it can wait. Can you push it on resinOS? I was looking into repos but it wasn't clear to me where should I open the issue. Just ref me or this issue, so that I can follow, thanks!

**Comment by craig-mulligan** [comment]
Sure see here: https://github.com/resin-os/resinos/issues/200 all resinOS issues are made on that repo.

**Comment by craig-mulligan** [comment]
Closing as this seems out of scope for now.
