### ISSUE TITLE
RPi3 hci0 not showing up

### ISSUE THREAD

**Issue by cskiraly** [Agile-IoT/agile-stack#9]
The linked resinOS image is not handling the RPi3 BLE adapter. `hciconfig` shows nothing.

Otherwise, with an external dongle, bluetooth works fine.

**Comment by cskiraly** [comment]
I have also tested with the RPi3 image (https://files.resin.io/resinos/raspberrypi3/2.0.0-beta.1/resin-dev.zip). Still no hci0. @craig-mulligan @shaunmulligan, is this a known issue? Is there a newer beta?

**Comment by craig-mulligan** [comment]
@cskiraly sorry to leave you hanging here. I hadn't tested on native BLE but we should get this sorted asap, I've reported the issue here: https://github.com/resin-os/resinos/issues/199 will try test later today.

**Comment by craig-mulligan** [comment]
In order to get the built-in BLE on rpi 3 working we need to patch source from the rpi foundation. 

An example: 
https://github.com/resin-io-projects/rpi3-bluetooth

**Comment by craig-mulligan** [comment]
This probably needs to be included in https://github.com/Agile-IoT/agile-ble @cskiraly

**Comment by cskiraly** [comment]
I'm missing the point. To me it seems it is more like a missing kernel module to handle the specific ble chip on the RPi3.

**Comment by cskiraly** [comment]
The magic command is `/usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow -`
Tested and works.

I think we need a customized image (or an init script) with this and with service bluetooth disabled.

**Comment by craig-mulligan** [comment]
Cool, most sense to me would be to have the BLE service run the init script that disables ble and runs the magic?

**Comment by cskiraly** [comment]
It depends on what is a prerequisite and what us part of the BLE service. Till now, prerequisite was hci available in the system and not used by others (i.e. no bluetoothd running in the host). This is generic over all platforms.
If we put the RPi3 specific init in the BLE service itself, we make it RPi3 specific.

**Comment by craig-mulligan** [comment]
Currently working on rpi3 occasionally some instability, sometimes you have to run the attach command multiple times.
